### ISSUE TITLE
An idea to streamline the process

### ISSUE THREAD

**Issue by maxim-fedotov-1997** [SavageCore/pd3-vault-cracker#20]
Howdy!
The way I saw it... Keypads do show when one button was used multiple times.
Would it be possible to make it work such a way that you could double-input the digit and have it show less of the combinations that are outright impossible?

Say... For example, pad has "3668" password. The current flow has me input 3 known digits and then weed out combos that I can't apply in the current situation (any that lack 2 six digits).
I feel like it would make it faster to operate with it if you were to make it happen (if possible).

Thanks in advance, and thanks again for such an awesome tool! :D

**Comment by SavageCore** [comment]
This was already thought about. See #19
